include(ExternalProject)

set(OPENJTALK_VERSION "1.11")
set(OPENJTALK_DIR "${CMAKE_CURRENT_BINARY_DIR}/oj")

set(OPENJTALK_CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX:PATH=${OPENJTALK_DIR}
  -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
  -DBUILD_SHARED_LIBS:BOOL=OFF
  -DHTS_ENGINE_INCLUDE_DIR:PATH=${HTS_ENGINE_DIR}/include
  ${EXTERNAL_CMAKE_ARGS}
)

if(WIN32)
  list(APPEND OPENJTALK_CMAKE_ARGS
    -DHTS_ENGINE_LIB:FILEPATH=${HTS_ENGINE_DIR}/lib/HTSEngine.lib
    -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=${CMAKE_MSVC_RUNTIME_LIBRARY}
  )
else()
  list(APPEND OPENJTALK_CMAKE_ARGS
    -DHTS_ENGINE_LIB:FILEPATH=${HTS_ENGINE_DIR}/lib/libHTSEngine.a
  )
endif()

ExternalProject_Add(
  openjtalk_external
  PREFIX "${CMAKE_CURRENT_BINARY_DIR}/o"
  URL "https://downloads.sourceforge.net/project/open-jtalk/Open%20JTalk/open_jtalk-${OPENJTALK_VERSION}/open_jtalk-${OPENJTALK_VERSION}.tar.gz"
  CMAKE_ARGS ${OPENJTALK_CMAKE_ARGS}
  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/OpenJTalk_CMakeLists.txt
    <SOURCE_DIR>/CMakeLists.txt
  BUILD_BYPRODUCTS
    ${OPENJTALK_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}openjtalk${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${OPENJTALK_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}mecab${CMAKE_STATIC_LIBRARY_SUFFIX}
)

add_dependencies(openjtalk_external hts_engine_external)
