include(ExternalProject)

set(OPENJTALK_VERSION "1.11")
set(OPENJTALK_DIR "${CMAKE_CURRENT_BINARY_DIR}/oj")

set(OPENJTALK_CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX:PATH=${OPENJTALK_DIR}
  -DCMAKE_BUILD_TYPE:STRING=${EXTERNAL_BUILD_TYPE}
  -DBUILD_SHARED_LIBS:BOOL=OFF
  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
  -DCMAKE_CXX_STANDARD:STRING=14
  -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
  -DHTS_ENGINE_INCLUDE_DIR:PATH=${HTS_ENGINE_DIR}/include
  ${EXTERNAL_CMAKE_ARGS}
)

if(WIN32)
  # CMAKE_MSVC_RUNTIME_LIBRARY is already passed via EXTERNAL_CMAKE_ARGS
  list(APPEND OPENJTALK_CMAKE_ARGS
    -DHTS_ENGINE_LIB:FILEPATH=${HTS_ENGINE_DIR}/lib/HTSEngine.lib
  )
else()
  list(APPEND OPENJTALK_CMAKE_ARGS
    -DHTS_ENGINE_LIB:FILEPATH=${HTS_ENGINE_DIR}/lib/libHTSEngine.a
  )
endif()

ExternalProject_Add(
  openjtalk_external
  PREFIX "${CMAKE_CURRENT_BINARY_DIR}/o"
  URL "https://downloads.sourceforge.net/project/open-jtalk/Open%20JTalk/open_jtalk-${OPENJTALK_VERSION}/open_jtalk-${OPENJTALK_VERSION}.tar.gz"
  CMAKE_ARGS ${OPENJTALK_CMAKE_ARGS}
  BUILD_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --config ${EXTERNAL_BUILD_TYPE}
  INSTALL_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --target install --config ${EXTERNAL_BUILD_TYPE}
  PATCH_COMMAND ${CMAKE_COMMAND}
    -DSOURCE_DIR=<SOURCE_DIR>
    -DCMAKE_SOURCE=${CMAKE_CURRENT_SOURCE_DIR}/cmake/OpenJTalk_CMakeLists.txt
    -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/patch_openjtalk.cmake
  BUILD_BYPRODUCTS
    ${OPENJTALK_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}openjtalk${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${OPENJTALK_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}mecab${CMAKE_STATIC_LIBRARY_SUFFIX}
)

add_dependencies(openjtalk_external hts_engine_external)
